spring:
  application:
    name: ruleForge-core

dubbo:
  application:
    id: ruleForge-core-provider
    name: ruleForge-core-provider
  provider:
    version: 1.0
  protocol:
    name: dubbo
    port: 28850
  registry:
    id: ruleForge-core-registry
    address: zookeeper://127.0.0.1:2181
    timeout: 20000
    simplified: true
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com\yunext\core\provider
  consumer:
    check: false
    version: 1.0
    timeout: 5000
liteflow:
  rule-source-ext-data-map:
    host: 127.0.0.1
    port: 6379
    #如果你没有用户名或密码可以不配置
    username:
    password:
    mode: sub
    pollingInterval: 5
    pollingStartTime: 1
    chainDataBase: 0
    chainKey: chains
    #如果你没有脚本组件，以下可以不配置
    scriptDataBase: 0
    scriptKey: scripts
