spring:
  application:
    name: ruleForge-core

dubbo:
  application:
    name: ruleForge-core-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com/yunext/core/provider
liteflow:
  rule-source-ext-data-map:
    host: 127.0.0.1
    port: 6379
    #如果你没有用户名或密码可以不配置
    username:
    password:
    mode: sub
    pollingInterval: 5
    pollingStartTime: 1
    chainDataBase: 1
    chainKey: chain_rules
    #如果你没有脚本组件，以下可以不配置
    scriptDataBase: 1
    scriptKey: chain_scripts
mqtt:
  username: spring_farm
  password: YCwn1dr1zCel0zAE
  server: tcp://127.0.0.1:1883
redisson-chain:
  timeout: 3000
  database: 1
  address: redis://127.0.0.1:6379
  password:
