spring:
  application:
    name: ruleForge-client-web
dubbo:
  application:
    id: ruleForge-client-web
    name: ruleForge-client-web
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: ruleForge-client-web-registry
    address: zookeeper://127.0.0.1:2181
    timeout: 20000
    simplified: true
  scan:
    base-packages: com/yunext/client/web/provider
#  consumer:
#    check: false
#    version: 1.0
#    timeout: 5000
